### ISSUE TITLE
Lightwave Integration stops showing current status. 

### ISSUE THREAD

**Issue by paularnol** [bigbadblunt/homeassistant-lightwave2#33]
Integration stops pulling data. Needing to reboot HA to see current status of lights/TRVs

**Comment by bigbadblunt** [comment]
Can you let me know the version and provide a log file with debugging enabled?

**Comment by raypanggh** [comment]
I have the same issue but with the LW921 thermostats. using v3.2.0 of the integration.  Reboots pull the current temperature, but they don't update after that.

Which log do you need? The HA log?

**Comment by bigbadblunt** [comment]
Yes please, with the following components set to debug:
```
logger:
  default: warning
  logs:
    lightwave2.lightwave2: debug
    custom_components.lightwave2: debug
```
Could you also try upgrading to the latest beta version and see if that is more reliable?
