### ISSUE TITLE
Understanding 'set_led_rgb'

### ISSUE THREAD

**Issue by bensmithuk** [bigbadblunt/homeassistant-lightwave2#36]
I am trying to set a dimmer LED to 1% at certain times (in a bedroom, close to a bed) but whatever value I set the app reports 11%. Is this deliberate or am I doing it wrong? Higher values seem to work as expected.

I don't know what the precision is on the LEDs but 1% seems dimmer to me than 11% and Lightwave's own Automations seem happy to apply it.

**Comment by bigbadblunt** [comment]
@bensmithuk I'm not sure what you're trying to do. I think you want to set the brightness of the actual light to 1%. You need to use the service `light.turn_on`, with `brightness_pct` equal to 1.

See https://www.home-assistant.io/integrations/light/

Generally it's these `light` service calls you should be using to control things.

`lightwave2.set_led_rgb` doesn't change the brightness of the actual device, it changes the colour of the status LED on the wall switch.

Let me know if I've misunderstood your problem.

**Comment by bensmithuk** [comment]
@bigbadblunt Sorry I wasn't clear.

I am using `lightwave2.set_led_rgb` to set the status LED of a dimmer device. I want to have it bright in daylight and dimmed at night for comfort in a bedroom.

When I use `lightwave2.set_led_rgb` I can't set the status LED to any value that results in a brightness below 11% (as reported by the Lightwave app) - even using `#000001` results in 11% status LED brightness.

I can apply lower values in Lightwave's own app and they appear dimmer than the 11% level (to me) so I assume the device can do what I want.

Example steps I am following:

1. Set Status LED to pale blue at 1% in Lightwave App and confirm appearance has changed on device.
2. Read attributes in developer tools:
    ```
    supported_color_modes:
      - brightness
    lwrf_switch: 0
    lwrf_dimLevel: 100
    lwrf_dimSetup: 139165696
    lwrf_bulbSetup: 10486272
    lwrf_protection: 0
    lwrf_power: 0
    lwrf_energy: 23
    lwrf_identify: 0
    lwrf_reset: 0
    lwrf_upgrade: 0
    lwrf_diagnostics: 37
    lwrf_periodOfBroadcast: 0
    lwrf_rgbColor: 514
    lrwf_product_code: L22EU
    current_power_w: 0
    friendly_name: Mirror Lights (Ensuite)
    supported_features: 1
    ```
    
3. Change status LED to another value through Lightwave app.
4. Use developer tools to apply the RGB value to the device.
    ```
    service: lightwave2.set_led_rgb
    data:
      entity_id: light.ensuite_mirror_lights
      rgb: '0x514'
    ```

Expected behaviour: Device status LED changes to same colour brightness as when the attributes were read (pale blue, 1% brightness).
Actual behaviour: Device status LED changes to correct colour but brightness level is 11%.
