### ISSUE TITLE
Feature Request: polling device

### ISSUE THREAD

**Issue by SGXander** [bigbadblunt/homeassistant-lightwave2#77]
The Non-public API is still the better of the two but even with the timed restart function still drops out for large chunks of time prompting a HA restart to fix. Could a device be chosen instead as a "monitor" device that would force a reconnection if it didn't report in for some time? If this was watching the consumption meter on the socket powering my HA server for example this would be a good way of detecting the connection drop and restarting.

**Comment by bigbadblunt** [comment]
How about i add a service call to force a reconnect? It would then be up to you to decide on the logic for when to invoke that call?

**Comment by SGXander** [comment]
That's even better, This way if they haven't reported in then it can be done with an automation and should be minimal outage too. I have it set to 28 minutes at the moment which seems to be the best time interval but between 21:00 and 07:00 it still seems to lose feedback completely so hoping this will fix it.

I assume LWRF haven't responded about the heartbeat?

**Comment by xela1** [comment]
Oh I understand what you're saying now, I thought you meant the response from your request, but you mean a state change triggered from your command instead, got it. That would work, not sure how easy to implement though

**Comment by bigbadblunt** [comment]
OK, I have done two things

1) added a service `lightwave2.reconnect` that forces a reconnect
2) added a sensor to the link that shows the last time an event was received (see screenshot below)

this should allow you to write whatever automation you'd like to send a signal and check for a response.

**Comment by garysargentpersonal** [comment]
@bigbadblunt any chance the sensor could have "seconds since last event received" rather than the timestamp? Would mean we don't have to attempt nasty date/time calculation just to see how long ago the last event was.

**Comment by garysargentpersonal** [comment]
Ok I have setup one automation which is triggering using "time pattern" using minutes as "/1" to run every minute. The actions are turn the LinkPlus LED off, then on again. This causes events to be received on the webhook.

Then I have a second automation which is a template trigger as follows:

```
{{ (as_timestamp(now()) - as_timestamp(states.sensor.linkplus_last_event_received.state)) | int > 140 }}
```

When that fires it sends me a notification, and calls the force reconnect.

I've configured the integration with a value of 0 so it doesn't do its own force reconnection.

Let's see how that goes...

**Comment by bigbadblunt** [comment]
Changing to "seconds since last event" is a bit problematic as then I have to keep updating the sensor every second. I'm not sure how to do that safely. 

Are you using the non-public API? The reconnect service only reconnects the non-public websocket so won't do anything on the public API.

**Comment by garysargentpersonal** [comment]
Ah yes good point on having to keep updating the sensor.

Yes I'm using the non-public API.

**Comment by garysargentpersonal** [comment]
Here is my full automation in case it helps anyone...

```
alias: Reconnect to Lightwave when no events received
description: ''
trigger:
  - platform: template
    value_template: >
      {{ (as_timestamp(now()) -
      as_timestamp(states.sensor.linkplus_last_event_received.state)) | int >
      140 }}
    id: events_not_received
  - platform: template
    value_template: >-
      {{ (as_timestamp(now()) -
      as_timestamp(states.sensor.linkplus_last_event_received.state)) | int >
      240 }}
    id: events_still_not_received
  - platform: time_pattern
    id: force_some_events
    minutes: /1
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: events_not_received
        sequence:
          - service: notify.pushover
            data:
              message: >-
                Stopped receiving Lightwave events in Home Assistant. Forcing
                reconnection.
          - service: lightwave2.reconnect
            data: {}
      - conditions:
          - condition: trigger
            id: events_still_not_received
        sequence:
          - service: notify.pushover
            data:
              message: >-
                Not receiving Lightwave events even after forcing a
                reconnection. Please restart HA.
      - conditions:
          - condition: trigger
            id: force_some_events
        sequence:
          - type: turn_off
            device_id: 0009161e043d5b7ffed765ed8f8be954
            entity_id: light.linkplus_led
            domain: light
          - type: turn_on
            device_id: 0009161e043d5b7ffed765ed8f8be954
            entity_id: light.linkplus_led
            domain: light
    default: []
mode: queued
```

**Comment by SGXander** [comment]
I'm going to give this a try when I get back but thank you for this! The only issue I can think of is that when reconnecting can you re-enumerate device state? I have been seeing a problem where the auto reconnect works but any physical presses while it was disconnected are not updated after reconnecting.
________________________________

**Comment by RGarrett93** [comment]
> Here is my full automation in case it helps anyone...
> 
> ```
> alias: Reconnect to Lightwave when no events received
> description: ''
> trigger:
>   - platform: template
>     value_template: >
>       {{ (as_timestamp(now()) -
>       as_timestamp(states.sensor.linkplus_last_event_received.state)) | int >
>       140 }}
>     id: events_not_received
>   - platform: template
>     value_template: >-
>       {{ (as_timestamp(now()) -
>       as_timestamp(states.sensor.linkplus_last_event_received.state)) | int >
>       240 }}
>     id: events_still_not_received
>   - platform: time_pattern
>     id: force_some_events
>     minutes: /1
> condition: []
> action:
>   - choose:
>       - conditions:
>           - condition: trigger
>             id: events_not_received
>         sequence:
>           - service: notify.pushover
>             data:
>               message: >-
>                 Stopped receiving Lightwave events in Home Assistant. Forcing
>                 reconnection.
>           - service: lightwave2.reconnect
>             data: {}
>       - conditions:
>           - condition: trigger
>             id: events_still_not_received
>         sequence:
>           - service: notify.pushover
>             data:
>               message: >-
>                 Not receiving Lightwave events even after forcing a
>                 reconnection. Please restart HA.
>       - conditions:
>           - condition: trigger
>             id: force_some_events
>         sequence:
>           - type: turn_off
>             device_id: 0009161e043d5b7ffed765ed8f8be954
>             entity_id: light.linkplus_led
>             domain: light
>           - type: turn_on
>             device_id: 0009161e043d5b7ffed765ed8f8be954
>             entity_id: light.linkplus_led
>             domain: light
>     default: []
> mode: queued
> ```

Thanks for sharing this, its a well written automation and seems to be working great for automatically reconnecting. I was trying to work out a solution auto reconnect and this automation solves it.

**Comment by SGXander** [comment]
+1 for @garysargentpersonal, using this pretty much as-is. Fingers crossed this sorts it!

@bigbadblunt the Link Plus LED on/off is like the Gen1 and not a toggle, not sure if it should be but the other G2 gear LEDs are.

**Comment by SGXander** [comment]
![Screenshot_20220516-070328_Home Assistant](https://user-images.githubusercontent.com/8619536/168533614-c4eaa129-0a01-48f7-9e0c-529a7ae34ef6.jpg)

So good news is it works^ I'm going to have a tweak later as it seems to fail if the connection is dropped before midnight but the next check is after midnight (something to do with the conversion maybe?)

Bad is that it still seems to die eventually though I think this may be down to it being in one automation? I'm going to split it out into 2 and see if that fixes it given the time stamps. Will also make sure I get logs next time it drops out.

**Comment by garysargentpersonal** [comment]
Interesting as when I compare to my outages - they are pretty much the same times as yours!

```
07:48:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
07:47:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
06:45:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
06:44:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
06:39:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
06:38:06 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
05:36:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
05:34:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
04:32:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
04:31:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
04:28:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
04:27:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
03:25:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
03:23:06 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
02:21:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
02:20:06 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
02:15:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
02:14:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
01:12:05 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
01:10:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
00:07:06 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
00:07:00 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
00:03:19 - Lightwave Events Connected turned on by Reconnect to Lightwave when no events received
00:03:05 - Lightwave Events Connected turned off by Reconnect to Lightwave when no events received
```

I now have a boolean helper entity that is true when events are being received, and false when not - this means I get a logbook entry and history of all changes in state.

I've also made the automation continue to send reconnect calls every minute after the initial one when it hasn't connected, up to the ten minute point where we give up. I've had some instances where the first reconnect didn't work, but a subsequent one would.

```
alias: Reconnect to Lightwave when no events received
description: ''
trigger:
  - platform: template
    value_template: >
      {{ (as_timestamp(now()) -
      as_timestamp(states.sensor.linkplus_last_event_received.state)) | int >
      140 }}
    id: events_not_received
  - platform: template
    value_template: >-
      {{ (as_timestamp(now()) -
      as_timestamp(states.sensor.linkplus_last_event_received.state)) | int >
      600 }}
    id: events_still_not_received
  - platform: time_pattern
    id: force_some_events
    minutes: /1
  - platform: template
    value_template: >-
      {{ (as_timestamp(now()) -
      as_timestamp(states.sensor.linkplus_last_event_received.state)) | int <
      140 }}
    id: events_received
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: events_not_received
        sequence:
          - service: notify.pushover
            data:
              message: >-
                Stopped receiving Lightwave events in Home Assistant. Forcing
                reconnection.
          - service: lightwave2.reconnect
            data: {}
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.lightwave_events_connected
      - conditions:
          - condition: trigger
            id: events_still_not_received
        sequence:
          - service: notify.pushover
            data:
              message: >-
                Not receiving Lightwave events even after forcing a
                reconnection. Please restart HA.
      - conditions:
          - condition: trigger
            id: force_some_events
        sequence:
          - type: turn_off
            device_id: 0009161e043d5b7ffed765ed8f8be954
            entity_id: light.linkplus_led
            domain: light
          - type: turn_on
            device_id: 0009161e043d5b7ffed765ed8f8be954
            entity_id: light.linkplus_led
            domain: light
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - if:
              - condition: template
                value_template: >-
                  {{ (as_timestamp(now()) -
                  as_timestamp(states.sensor.linkplus_last_event_received.state))
                  | int > 240 }}
            then:
              - service: lightwave2.reconnect
                data: {}
      - conditions:
          - condition: trigger
            id: events_received
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.lightwave_events_connected
    default: []
mode: queued
```
