### ISSUE TITLE
Sorry not an issue more help please

### ISSUE THREAD

**Issue by ste19m** [bigbadblunt/homeassistant-lightwave2#85]
How do I go about making an automation for the light switches on multi press? Ie double press up would turn the extractor on I can see it’s capable but I can’t work out how to do it

**Comment by SGXander** [comment]
My example here listens for a double-down press on any of 3 dimmers and will turn lights off in both connecting rooms

```
alias: Lights - Trigger Off - Kitchen/Utility
description: ''
trigger:
  - platform: event
    event_type: lightwave2.click
    event_data:
      entity_id: light.r04_d1
      code: 4354
  - platform: event
    event_type: lightwave2.click
    event_data:
      entity_id: light.r04_d2
      code: 4354
  - platform: event
    event_type: lightwave2.click
    event_data:
      entity_id: light.r05_d1
      code: 4354
condition: []
action:
  - parallel:
      - type: turn_off
        device_id: 0406c0429982e9d10ae7093d57e69511
        entity_id: light.r04_d1
        domain: light
      - type: turn_off
        device_id: d70d3e046709defba87c36032b32b796
        entity_id: light.r05_d1
        domain: light
mode: single
```

main thing you want is the trigger to be an event of type lightwave2.click then to fill in entity data with your device name and the code from the homepage: https://github.com/bigbadblunt/homeassistant-lightwave2
